using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerStat : MonoBehaviour {
    public int hp;
    public int speed;
    public int dash;
    public float sprint;
    public int teleP; //Telekinesis Points
    public int laserP; //Laser Points
    public int flying_speed;
    public int max_mana;
    public int regen_mana; //number of manage regenerated by seconds
    public int current_mana;
    // add settings for game keys
    // Start is called before the first frame update
    void Start() {
        hp = 100;
        speed = 25;
        dash = 90;
        sprint = 1.6f;
        teleP = 1800;
        laserP = 30;
        flying_speed = 190;
        regen_mana = 10;
        max_mana = 180;
        current_mana = 180;
        Invoke("update_mana", 0.1f);
    }

    void update_mana() {
        if (current_mana < max_mana) {
            current_mana += regen_mana / 10;
            current_mana = current_mana > max_mana ? max_mana : current_mana;
        }
    }

    public int get_hp() {
        return hp;
    }
    public int heal(int amount) {
        hp += amount;
        hp = hp > 100 ? 100 : hp;
        return hp;
    }
    public int get_speed() {
        return speed;
    }
    public int speed_up(int amount) {
        speed += amount;
        return speed;
    }
    public int get_dash() {
        return dash;
    }
    public int add_dash(int amount) {
        dash += amount;
        return dash;
    }
    public float get_spint() {
        return sprint;
    }
    public int add_sprint(int amount) {
        sprint += (float) amount;
        return (int) sprint;
    }
    public int get_teleP() {
        return teleP;
    }
    public int add_teleP(int amount) {
        teleP += amount;
        return teleP;
    }
    public int get_laserP() {
        return laserP;
    }
    public int add_laserP(int amount) {
        laserP += amount;
        return laserP;
    }
    public int get_flying_speed() {
        return flying_speed;
    }
    public int add_flying_speed(int amount) {
        flying_speed += amount;
        return flying_speed;
    }
    public int get_current_mana() {
        return current_mana;
    }
    public int add_current_mana(int amount) {
        current_mana += amount;
        current_mana = current_mana > max_mana ? max_mana : current_mana;
        return current_mana;
    }
    public int get_max_mana() {
        return max_mana;
    }
    public int add_max_mana(int amount) {
        max_mana += amount;
        return max_mana;
    }
    public int get_regen_mana() {
        return regen_mana;
    }
    public int add_regen_mana(int amount) {
        regen_mana += amount;
        return regen_mana;
    }
}
